# Generated by Django 5.0.6 on 2026-04-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('type_of_room', models.CharField(choices=[('casal', 'Casal'), ('solteiro', 'Solteiro'), ('Suite Princes', 'Suite Princes'), ('suite', 'Suite')], max_length=20)),
                ('adult', models.IntegerField(default=0)),
                ('child', models.IntegerField(default=0)),
            ],
        ),
    ]
